/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Controller.EncomendaController;
import Util.Enums;
import Util.Error;
import Util.TelaHandler;
import Util.Helper;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JRadioButtonMenuItem;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import org.json.JSONArray;
import org.json.JSONObject;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Matheus
 */
public class Encomenda extends javax.swing.JFrame {
    private JFrame windowsBack;
    private int cidadeOrigemID;
    private int PessoaID;
    private int destinatarioID;
    private TelaHandler tratarEventos;
    private ArrayList<JTextField> camposAtivar;
    private Util.Enums.NaturezaPessoa tipoRemetente;
    private Util.Enums.NaturezaPessoa tipoDestinatario;
    private JSONObject jsonPersistencia;
    private String busca;

    public String getBusca() {
        return busca;
    }

    public void setBusca(String busca) {
        this.busca = busca;
    }
    /**
     * Creates new form Encomenda
     * @param windowsBack
     */
    public Encomenda(JFrame windowsBack) {
        initComponents();
        Init(windowsBack);
        
    }
    private void PreencheComboBox(List<JSONObject> list, JComboBox combo, String name){
        list.forEach((j) -> {
            combo.addItem(j.get(name));
        });
    }
    private void InitCamposBusca(boolean habilitaBusca){
        jtfDestinatarioNome.setText("Busque um destinatário");
        jtfRemetenteNome.setText("Busque um remetente");
        jtfCidadeDestinoNome.setText("Busque uma cidade");
        jtfCidadeOrigemNome.setText("Busque uma cidade");
        jbBuscaRemetente.setEnabled(habilitaBusca);
        jbBuscaDestinatario.setEnabled(habilitaBusca);
        jbBuscaCidadeDestino.setEnabled(habilitaBusca);
        jbBuscaCidadeOrigem.setEnabled(habilitaBusca);
    
    }
    private void Init(JFrame windowsBack){
        this.windowsBack = windowsBack;
        JComboBox tipoEmbalagemCombo = new JComboBox();
        this.setLocationRelativeTo(null);
        TableColumn colunaDesc = jtbItensEncomenda.getColumnModel().getColumn(0);
        TableColumn colunaPeso = jtbItensEncomenda.getColumnModel().getColumn(1);
        TableColumn colunaTipoEmb = jtbItensEncomenda.getColumnModel().getColumn(2);
        colunaDesc.setMaxWidth(800);
        colunaPeso.setMaxWidth(100);
        colunaTipoEmb.setMaxWidth(500);
        jtbItensEncomenda.setRowHeight(19);
        jtbItensEncomenda.setCellSelectionEnabled(true);
        jsonPersistencia  = new JSONObject();
        
        
        tratarEventos = new TelaHandler(jbIncluir, jbGravar, jbCancelar, jbExluir,jbConsultar);
        camposAtivar = new ArrayList<>();
        camposAtivar.add(jtfRemetenteCodigo);
        camposAtivar.add(jtfDestinatarioCodigo);
        camposAtivar.add(jtfRuaRemetente);
        camposAtivar.add(jtfBairroRemetente);
        camposAtivar.add(jtfCepRemetente);
        camposAtivar.add(jtfNumeroRemetente);
        camposAtivar.add(jtfComplementoRemetente);
        camposAtivar.add(jtfCidadeOrigemCodigo);
        camposAtivar.add(jtfRuaDestino);
        camposAtivar.add(jtfBairroDestino);
        camposAtivar.add(jtfCepDestino);
        camposAtivar.add(jtfNumeroDestino);
        camposAtivar.add(jtfComplementoDestino);
        camposAtivar.add(jtfCidadeDestinoCodigo);
        camposAtivar.add((JTextField)jftDataCadastro);
        tratarEventos.setCampos(camposAtivar);
        tratarEventos.setTabela(jtbItensEncomenda);
        
        
        PreencheComboBox((new Controller.TipoEmbalagemController()).GetAll(), tipoEmbalagemCombo,"descricao");
        if(tipoEmbalagemCombo.getItemCount() > 0)
            tipoEmbalagemCombo.setSelectedIndex(0);
        
        colunaTipoEmb.setCellEditor(new DefaultCellEditor(tipoEmbalagemCombo));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        ModalidadeFrete = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfRemetenteNome = new javax.swing.JTextField();
        jbBuscaRemetente = new javax.swing.JButton();
        jtfRemetenteCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfDestinatarioCodigo = new javax.swing.JTextField();
        jtfDestinatarioNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jbBuscaDestinatario = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jtfRuaRemetente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtfBairroRemetente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtfCepRemetente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtfNumeroRemetente = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtfComplementoRemetente = new javax.swing.JTextField();
        jtfCidadeOrigemCodigo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtfCidadeOrigemNome = new javax.swing.JTextField();
        jbBuscaCidadeOrigem = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jtfRuaDestino = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtfBairroDestino = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jtfCepDestino = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jtfNumeroDestino = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jtfComplementoDestino = new javax.swing.JTextField();
        jtfCidadeDestinoNome = new javax.swing.JTextField();
        jtfCidadeDestinoCodigo = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jbBuscaCidadeDestino = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbItensEncomenda = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jrFreteNormal = new javax.swing.JRadioButton();
        jrFreteRapido = new javax.swing.JRadioButton();
        jrFreteSuperRapido = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        jlValorTotal = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jbCalcular = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jbIncluir = new javax.swing.JButton();
        jbGravar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbConsultar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jlStatusEncomenda = new javax.swing.JLabel();
        jbExluir = new javax.swing.JButton();
        jtfCodigo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jftDataCadastro = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Encomenda");
        setMinimumSize(new java.awt.Dimension(932, 507));
        setPreferredSize(new java.awt.Dimension(906, 623));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Remetente\\Destinatario"));
        jPanel4.setLayout(null);

        jLabel1.setText("Remetente");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(20, 30, 53, 14);

        jtfRemetenteNome.setEditable(false);
        jtfRemetenteNome.setText("Busque um remetente");
        jtfRemetenteNome.setEnabled(false);
        jtfRemetenteNome.setName("nome do remetente"); // NOI18N
        jPanel4.add(jtfRemetenteNome);
        jtfRemetenteNome.setBounds(78, 47, 240, 20);

        jbBuscaRemetente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/search.png"))); // NOI18N
        jbBuscaRemetente.setEnabled(false);
        jbBuscaRemetente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscaRemetenteActionPerformed(evt);
            }
        });
        jPanel4.add(jbBuscaRemetente);
        jbBuscaRemetente.setBounds(328, 47, 36, 20);

        jtfRemetenteCodigo.setEditable(false);
        jtfRemetenteCodigo.setEnabled(false);
        jtfRemetenteCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfRemetenteCodigoActionPerformed(evt);
            }
        });
        jPanel4.add(jtfRemetenteCodigo);
        jtfRemetenteCodigo.setBounds(16, 47, 60, 20);

        jLabel2.setText("Nome");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(80, 30, 57, 14);

        jLabel3.setText("Destinatário");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(20, 80, 58, 14);

        jtfDestinatarioCodigo.setEditable(false);
        jtfDestinatarioCodigo.setEnabled(false);
        jPanel4.add(jtfDestinatarioCodigo);
        jtfDestinatarioCodigo.setBounds(18, 100, 60, 20);

        jtfDestinatarioNome.setEditable(false);
        jtfDestinatarioNome.setText("Busque um destinatário");
        jtfDestinatarioNome.setEnabled(false);
        jtfDestinatarioNome.setName("nome do destinatário"); // NOI18N
        jPanel4.add(jtfDestinatarioNome);
        jtfDestinatarioNome.setBounds(80, 100, 240, 20);

        jLabel4.setText("Nome");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(90, 80, 57, 14);

        jbBuscaDestinatario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/search.png"))); // NOI18N
        jbBuscaDestinatario.setEnabled(false);
        jbBuscaDestinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscaDestinatarioActionPerformed(evt);
            }
        });
        jPanel4.add(jbBuscaDestinatario);
        jbBuscaDestinatario.setBounds(330, 100, 36, 20);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/plus-button.png"))); // NOI18N
        jButton1.setText("Novo Remetente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(270, 10, 140, 30);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 0, 420, 150);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Coleta\\Destino"));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço De Coleta"));

        jtfRuaRemetente.setEnabled(false);
        jtfRuaRemetente.setName("rua de coleta"); // NOI18N

        jLabel8.setText("Rua");

        jLabel9.setText("Bairro");

        jtfBairroRemetente.setEnabled(false);
        jtfBairroRemetente.setName("bairro de coleta"); // NOI18N

        jLabel10.setText("Cep");

        jtfCepRemetente.setEnabled(false);
        jtfCepRemetente.setName("cep de coleta"); // NOI18N

        jLabel11.setText("Numero");

        jtfNumeroRemetente.setEnabled(false);
        jtfNumeroRemetente.setName("numero do endereço de coleta"); // NOI18N

        jLabel12.setText("Complemento");

        jtfComplementoRemetente.setEnabled(false);

        jtfCidadeOrigemCodigo.setEditable(false);
        jtfCidadeOrigemCodigo.setEnabled(false);

        jLabel13.setText("Cidade");

        jtfCidadeOrigemNome.setEditable(false);
        jtfCidadeOrigemNome.setText("Busque uma cidade");
        jtfCidadeOrigemNome.setEnabled(false);
        jtfCidadeOrigemNome.setName("nome da cidade de coleta"); // NOI18N

        jbBuscaCidadeOrigem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/search.png"))); // NOI18N
        jbBuscaCidadeOrigem.setEnabled(false);
        jbBuscaCidadeOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscaCidadeOrigemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfRuaRemetente)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jtfBairroRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfCepRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(154, 154, 154)
                                .addComponent(jLabel10)
                                .addGap(78, 78, 78)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfNumeroRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel11)))))
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel12)
                                .addGap(0, 44, Short.MAX_VALUE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfComplementoRemetente))))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel13)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jtfCidadeOrigemCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfCidadeOrigemNome, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbBuscaCidadeOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfRuaRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfBairroRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCepRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNumeroRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfComplementoRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel13)
                .addGap(2, 2, 2)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfCidadeOrigemCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfCidadeOrigemNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbBuscaCidadeOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço De Destino"));
        jPanel11.setLayout(null);

        jLabel15.setText("Rua");
        jPanel11.add(jLabel15);
        jLabel15.setBounds(16, 16, 19, 14);

        jtfRuaDestino.setEnabled(false);
        jtfRuaDestino.setName("rua de destino"); // NOI18N
        jPanel11.add(jtfRuaDestino);
        jtfRuaDestino.setBounds(16, 36, 446, 20);

        jLabel16.setText("Bairro");
        jPanel11.add(jLabel16);
        jLabel16.setBounds(16, 62, 28, 14);

        jtfBairroDestino.setEnabled(false);
        jtfBairroDestino.setName("bairro de destino"); // NOI18N
        jPanel11.add(jtfBairroDestino);
        jtfBairroDestino.setBounds(16, 82, 176, 20);

        jLabel17.setText("Cep");
        jPanel11.add(jLabel17);
        jLabel17.setBounds(198, 62, 19, 14);

        jtfCepDestino.setEnabled(false);
        jtfCepDestino.setName("cep de destino"); // NOI18N
        jPanel11.add(jtfCepDestino);
        jtfCepDestino.setBounds(198, 82, 91, 20);

        jLabel18.setText("Numero");
        jPanel11.add(jLabel18);
        jLabel18.setBounds(298, 62, 37, 14);

        jtfNumeroDestino.setEnabled(false);
        jtfNumeroDestino.setName("número do endereço de destino"); // NOI18N
        jPanel11.add(jtfNumeroDestino);
        jtfNumeroDestino.setBounds(295, 82, 50, 20);

        jLabel19.setText("Complemento");
        jPanel11.add(jLabel19);
        jLabel19.setBounds(353, 62, 65, 14);

        jtfComplementoDestino.setEnabled(false);
        jPanel11.add(jtfComplementoDestino);
        jtfComplementoDestino.setBounds(351, 82, 111, 20);

        jtfCidadeDestinoNome.setEditable(false);
        jtfCidadeDestinoNome.setText("Busque uma cidade");
        jtfCidadeDestinoNome.setEnabled(false);
        jtfCidadeDestinoNome.setName("nome da cidade de destino"); // NOI18N
        jPanel11.add(jtfCidadeDestinoNome);
        jtfCidadeDestinoNome.setBounds(81, 120, 230, 20);

        jtfCidadeDestinoCodigo.setEditable(false);
        jtfCidadeDestinoCodigo.setEnabled(false);
        jPanel11.add(jtfCidadeDestinoCodigo);
        jtfCidadeDestinoCodigo.setBounds(16, 120, 59, 20);

        jLabel21.setText("Cidade");
        jPanel11.add(jLabel21);
        jLabel21.setBounds(16, 104, 33, 14);

        jbBuscaCidadeDestino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/search.png"))); // NOI18N
        jbBuscaCidadeDestino.setEnabled(false);
        jbBuscaCidadeDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscaCidadeDestinoActionPerformed(evt);
            }
        });
        jPanel11.add(jbBuscaCidadeDestino);
        jbBuscaCidadeDestino.setBounds(320, 120, 36, 20);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jSeparator1)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        jPanel3.add(jPanel5);
        jPanel5.setBounds(420, 0, 500, 360);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Itens"));

        jtbItensEncomenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descricao", "Peso(KG)", "Tipo Embalagem"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtbItensEncomenda.setEnabled(false);
        jtbItensEncomenda.setName("Itens"); // NOI18N
        jtbItensEncomenda.getTableHeader().setReorderingAllowed(false);
        jtbItensEncomenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtbItensEncomendaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtbItensEncomendaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtbItensEncomenda);
        if (jtbItensEncomenda.getColumnModel().getColumnCount() > 0) {
            jtbItensEncomenda.getColumnModel().getColumn(0).setResizable(false);
            jtbItensEncomenda.getColumnModel().getColumn(1).setResizable(false);
            jtbItensEncomenda.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel2);
        jPanel2.setBounds(0, 350, 920, 170);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Modalidade Tranporte"));

        jrFreteNormal.setBackground(new java.awt.Color(255, 255, 255));
        ModalidadeFrete.add(jrFreteNormal);
        jrFreteNormal.setText("Normal");
        jrFreteNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrFreteNormalActionPerformed(evt);
            }
        });

        jrFreteRapido.setBackground(new java.awt.Color(255, 255, 255));
        ModalidadeFrete.add(jrFreteRapido);
        jrFreteRapido.setText("Rápido");

        jrFreteSuperRapido.setBackground(new java.awt.Color(255, 255, 255));
        ModalidadeFrete.add(jrFreteSuperRapido);
        jrFreteSuperRapido.setText("Super Rápido");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrFreteNormal)
                    .addComponent(jrFreteRapido)
                    .addComponent(jrFreteSuperRapido))
                .addGap(0, 49, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jrFreteNormal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrFreteRapido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrFreteSuperRapido)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel6);
        jPanel6.setBounds(0, 150, 150, 100);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Totalização"));

        jlValorTotal.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 26)); // NOI18N
        jlValorTotal.setForeground(new java.awt.Color(51, 51, 255));
        jlValorTotal.setText("0,00");

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 26)); // NOI18N
        jLabel6.setText("R$:");

        jbCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/cash-register.png"))); // NOI18N
        jbCalcular.setText("Calcular");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel8);
        jPanel8.setBounds(150, 150, 270, 100);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Rastreamento"));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 0, 26)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel9);
        jPanel9.setBounds(0, 250, 420, 100);

        jTabbedPane1.addTab("Dados Principais", jPanel3);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Histórico de Distribuidoras"));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 629, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Distribuidora", jPanel7);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 915, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Informações", jPanel13);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 30, 920, 510);

        jbIncluir.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jbIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/IncluirIcon.png"))); // NOI18N
        jbIncluir.setText("Incluir");
        jbIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIncluirActionPerformed(evt);
            }
        });
        jPanel1.add(jbIncluir);
        jbIncluir.setBounds(170, 550, 100, 30);

        jbGravar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jbGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/SaveIcon.png"))); // NOI18N
        jbGravar.setText("Gravar");
        jbGravar.setEnabled(false);
        jbGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGravarActionPerformed(evt);
            }
        });
        jPanel1.add(jbGravar);
        jbGravar.setBounds(280, 550, 110, 30);

        jbCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/CancelIcon.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.setEnabled(false);
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jbCancelar);
        jbCancelar.setBounds(400, 550, 110, 30);

        jbConsultar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/search.png"))); // NOI18N
        jbConsultar.setText("Consultar");
        jbConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(jbConsultar);
        jbConsultar.setBounds(630, 550, 120, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Status:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(650, 0, 50, 30);

        jlStatusEncomenda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlStatusEncomenda.setForeground(new java.awt.Color(102, 204, 0));
        jPanel1.add(jlStatusEncomenda);
        jlStatusEncomenda.setBounds(700, 0, 200, 30);

        jbExluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbExluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/trash.png"))); // NOI18N
        jbExluir.setText("Excluir");
        jbExluir.setEnabled(false);
        jbExluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExluirActionPerformed(evt);
            }
        });
        jPanel1.add(jbExluir);
        jbExluir.setBounds(520, 550, 100, 30);
        jPanel1.add(jtfCodigo);
        jtfCodigo.setBounds(60, 0, 70, 20);

        jLabel14.setText("Codigo:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(20, 0, 37, 20);

        jftDataCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jftDataCadastro.setEnabled(false);
        jPanel1.add(jftDataCadastro);
        jftDataCadastro.setBounds(550, 10, 80, 20);
        try {
            MaskFormatter mascara = new MaskFormatter("##/##/####");
            mascara.setPlaceholderCharacter('_');
            jftDataCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mascara));

        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel20.setText("Data de cadastro:");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(460, 10, 90, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 940, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscaRemetenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscaRemetenteActionPerformed
       // Helper.ShowDialog(this,new BuscaPessoaEncomenda(this,jtfRemetenteNome,jtfRemetenteCodigo,PessoaID, tipoRemetente));
       this.busca = "Remetente";
        Helper.ShowDialog(this,new EncomendaBuscaPessoa(this));
        
     
    }//GEN-LAST:event_jbBuscaRemetenteActionPerformed

    private void jbBuscaDestinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscaDestinatarioActionPerformed
        //Helper.ShowDialog(this,new BuscaPessoaEncomenda(this,jtfDestinatarioNome,jtfDestinatarioCodigo,destinatarioID,tipoDestinatario));
        this.busca = "Destinatario";
        Helper.ShowDialog(this,new EncomendaBuscaPessoa(this));
    }//GEN-LAST:event_jbBuscaDestinatarioActionPerformed

    private void jbConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbConsultarActionPerformed

    private void jbBuscaCidadeDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscaCidadeDestinoActionPerformed
        Helper.ShowDialog(this,new FreteBuscarCidade(this,jtfCidadeDestinoNome,jtfCidadeDestinoCodigo, cidadeOrigemID));
    }//GEN-LAST:event_jbBuscaCidadeDestinoActionPerformed

    private void jbBuscaCidadeOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscaCidadeOrigemActionPerformed
         Helper.ShowDialog(this,new FreteBuscarCidade(this,jtfCidadeOrigemNome,jtfCidadeOrigemCodigo,cidadeOrigemID));
    }//GEN-LAST:event_jbBuscaCidadeOrigemActionPerformed

    private void jbIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIncluirActionPerformed
        jtfCodigo.setEnabled(false);
        tratarEventos.ativaGravar(true);
        InitCamposBusca(true);
        ModalidadeFrete.clearSelection();
        Calendar cal = new GregorianCalendar();
        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
        jftDataCadastro.setText(formatador.format(cal.getTime()));
    }//GEN-LAST:event_jbIncluirActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        tratarEventos.ativaGravar(false);
        jtfCodigo.setEnabled(true);
        InitCamposBusca(false);
        ModalidadeFrete.clearSelection();

    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jrFreteNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrFreteNormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrFreteNormalActionPerformed

    private void jbGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGravarActionPerformed
        JSONObject jsonAux;
        JSONObject jsonObjeto;
        JSONArray jsonArrayObjetos = new JSONArray();
        
        try {
            Util.Validacao.freteRadioButtonSelected(ModalidadeFrete);
            Util.Validacao.InputToString(jtfRemetenteNome);
            Util.Validacao.InputToString(jtfDestinatarioNome);
            Util.Validacao.InputToString(jtfRuaRemetente);
            Util.Validacao.InputToString(jtfBairroRemetente);
            Util.Validacao.InputToString(jtfCepRemetente);
            Util.Validacao.InputToString(jtfNumeroRemetente);
            Util.Validacao.InputToString(jtfRuaDestino);
            Util.Validacao.InputToString(jtfBairroDestino);
            Util.Validacao.InputToString(jtfCepDestino);
            Util.Validacao.InputToString(jtfNumeroDestino);
            Util.Validacao.InputToString(jtfCidadeOrigemNome);
            Util.Validacao.InputToString(jtfCidadeDestinoNome);

            Util.Validacao.InputToString(jtfCidadeDestinoNome);
            Util.Validacao.itensjTable(jtbItensEncomenda);
            
            
            /*GERAÇÃO DO JSON PARA A PERSISTENCIA*/
            
            /*REMETENTE*/
            jsonAux = new JSONObject();
            jsonAux.put("codigo", jtfRemetenteCodigo.getText());
            if(tipoRemetente.compareTo(Util.Enums.NaturezaPessoa.Fisica) == 0)
                jsonAux.put("nome", jtfRemetenteNome.getText());
            else
                jsonAux.put("nomeFantasia", jtfRemetenteNome.getText());
            
            jsonAux.put("naturezaPessoa", tipoRemetente);
            jsonPersistencia.put("emitente", jsonAux);
            
             /*FIM REMETENTE*/
            
              /*DESTINATARIO*/
            jsonAux = new JSONObject();
            jsonAux.put("codigo", jtfDestinatarioCodigo.getText());
             if(tipoDestinatario.compareTo(Util.Enums.NaturezaPessoa.Fisica) == 0)
                jsonAux.put("nome", jtfDestinatarioNome.getText());
            else
                 jsonAux.put("nomeFantasia", jtfDestinatarioNome.getText());
             
            jsonAux.put("naturezaPessoa", tipoDestinatario);
            jsonPersistencia.put("destinatario", jsonAux);
            
             /*FIM DESTINATARIO*/
             
             
            /*ENDERECO REMETENTE*/
            
            jsonAux =  new JSONObject();
            jsonAux.put("rua", jtfRuaRemetente.getText());
            jsonAux.put("bairro", jtfBairroRemetente.getText());
            jsonAux.put("cep", jtfCepRemetente.getText());
            jsonAux.put("numero", jtfNumeroRemetente.getText());
            jsonAux.put("complemento", jtfComplementoRemetente.getText());
            jsonAux.put("cidade", jtfCidadeOrigemCodigo.getText());

            jsonPersistencia.put("endColeta", jsonAux);
            
            /*FIM ENDERECO REMETENTE*/

            
            /*ENDERECO DESTINATARIO*/
            jsonAux = new JSONObject();
            jsonAux.put("rua", jtfRuaDestino.getText());
            jsonAux.put("bairro", jtfBairroDestino.getText());
            jsonAux.put("cep", jtfCepDestino.getText());
            jsonAux.put("numero", jtfNumeroDestino.getText());
            jsonAux.put("complemento", jtfComplementoDestino.getText());
            jsonAux.put("cidade", jtfCidadeDestinoCodigo.getText());

            jsonPersistencia.put("endDestino", jsonAux);
            
            /*FIM ENDERECO REMETENTE*/
            
            /*ITENS DA ENCOMENDA*/
            for(int i = 0 ; i< jtbItensEncomenda.getRowCount(); i++){
                jsonObjeto = new JSONObject();
                jsonAux = new JSONObject();
                jsonObjeto.put("descricao", jtbItensEncomenda.getModel().getValueAt(i, 0));
                jsonObjeto.put("peso", jtbItensEncomenda.getModel().getValueAt(i, 1));
                String jcTipoEmbalagem = (String) jtbItensEncomenda.getValueAt(i, 2);
                jsonAux.put("descricao", jcTipoEmbalagem);
                jsonObjeto.put("tipoEmbalagem",jsonAux);
                jsonArrayObjetos.put(jsonObjeto);
                
            }
            jsonPersistencia.put("objetos", jsonArrayObjetos);
            
            
            /*FIM ITENS DA ENCOMENDA*/
            
            /*TIPO DO FRETE ESCOLHIDO*/
            if(jrFreteNormal.isSelected())
                jsonPersistencia.put("tipoFrete", Util.Enums.TipoFreteEncomenda.Normal);
            else if(jrFreteRapido.isSelected())
                jsonPersistencia.put("tipoFrete", Util.Enums.TipoFreteEncomenda.Rapido);
            else
                jsonPersistencia.put("tipoFrete", Util.Enums.TipoFreteEncomenda.SuperRapido);
            
            /*FIM TIPO DE FRETE */
            if(jlStatusEncomenda.getText().equals(""))
                jsonPersistencia.put("status", Util.Enums.StatusEncomenda.AguardandoColeta);
            else if(jlStatusEncomenda.getText().equals("Em Transito")){
                jsonPersistencia.put("status", Util.Enums.StatusEncomenda.EmTransito);
            }else
                jsonPersistencia.put("status", Util.Enums.StatusEncomenda.Entregue);
            
            jsonPersistencia.put("dataCadastro", jftDataCadastro.getText());
            /*FINAL GERAÇÃO JSON DE PERSISTÊNCIA*/
            EncomendaController encomendaCntrl = new EncomendaController();
            if(encomendaCntrl.Save(jsonPersistencia)){
                 jtfCodigo.setEnabled(true);
                 InitCamposBusca(false);
                 tratarEventos.ativaGravar(false);
                 JOptionPane.showMessageDialog(null, "Encomenda gravada com sucesso!");
            }
        } catch (Error ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro ao Gravar", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jbGravarActionPerformed

    public int getCidadeOrigemID() {
        return cidadeOrigemID;
    }

    public int getPessoaID() {
        return PessoaID;
    }

    public int getDestinatarioID() {
        return destinatarioID;
    }

    public ArrayList<JTextField> getCamposAtivar() {
        return camposAtivar;
    }

    public Enums.NaturezaPessoa getTipoRemetente() {
        return tipoRemetente;
    }
    public void setTipoRemetente(Enums.NaturezaPessoa tipo){
        this.tipoRemetente = tipo;
    }
    public void setTipoDestinatario(Enums.NaturezaPessoa tipo){
        this.tipoDestinatario = tipo;
    }

    public Enums.NaturezaPessoa getTipoDestinatario() {
        return tipoDestinatario;
    }

    public JSONObject getJsonPersistencia() {
        return jsonPersistencia;
    }

    public ButtonGroup getModalidadeFrete() {
        return ModalidadeFrete;
    }

    public JRadioButtonMenuItem getjRadioButtonMenuItem1() {
        return jRadioButtonMenuItem1;
    }

    public JButton getJbBuscaCidadeOrigem() {
        return jbBuscaCidadeOrigem;
    }

    public JButton getJbBuscaRemetente() {
        return jbBuscaRemetente;
    }

    public JButton getJbBuscaRemetente1() {
        return jbBuscaDestinatario;
    }

    public JButton getJbCalcular() {
        return jbCalcular;
    }

    public JButton getJbCancelar() {
        return jbCancelar;
    }

    public JButton getJbConsultar() {
        return jbConsultar;
    }

    public JButton getJbExluir() {
        return jbExluir;
    }

    public JButton getJbGravar() {
        return jbGravar;
    }

    public JButton getJbIncluir() {
        return jbIncluir;
    }

    public JLabel getJlStatusEncomenda() {
        return jlStatusEncomenda;
    }

    public JLabel getJlValorTotal() {
        return jlValorTotal;
    }

    public JRadioButton getJrFreteNormal() {
        return jrFreteNormal;
    }

    public JRadioButton getJrFreteRapido() {
        return jrFreteRapido;
    }

    public JRadioButton getJrFreteSuperRapido() {
        return jrFreteSuperRapido;
    }

    public JTable getJtbItensEncomenda() {
        return jtbItensEncomenda;
    }

    public JTextField getJtfBairro() {
        return jtfBairroRemetente;
    }

    public JTextField getJtfBairroDestino() {
        return jtfBairroDestino;
    }

    public JTextField getJtfCep() {
        return jtfCepRemetente;
    }

    public JTextField getJtfCepDestino() {
        return jtfCepDestino;
    }

    public JTextField getJtfCidadeDestinoCodigo() {
        return jtfCidadeDestinoCodigo;
    }

    public JTextField getJtfCidadeDestinoNome() {
        return jtfCidadeDestinoNome;
    }

    public JTextField getJtfCidadeOrigemCodigo() {
        return jtfCidadeOrigemCodigo;
    }

    public JTextField getJtfCidadeOrigemNome() {
        return jtfCidadeOrigemNome;
    }

    public JTextField getJtfComplemento() {
        return jtfComplementoRemetente;
    }

    public JTextField getJtfComplementoDestino() {
        return jtfComplementoDestino;
    }

    public JTextField getJtfDestinatarioCodigo() {
        return jtfDestinatarioCodigo;
    }

    public JTextField getJtfDestinatarioNome() {
        return jtfDestinatarioNome;
    }

    public JTextField getJtfNumero() {
        return jtfNumeroRemetente;
    }

    public JTextField getJtfNumeroDestino() {
        return jtfNumeroDestino;
    }

    public JTextField getJtfRemetenteCodigo() {
        return jtfRemetenteCodigo;
    }

    public JTextField getJtfRemetenteNome() {
        return jtfRemetenteNome;
    }

    public JTextField getJtfRua() {
        return jtfRuaRemetente;
    }

    public JTextField getJtfRuaDestino() {
        return jtfRuaDestino;
    }
    private void jtbItensEncomendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbItensEncomendaKeyPressed
        int linhaSelecionada =  jtbItensEncomenda.getSelectedRow();
        int colunaSelecionada =  jtbItensEncomenda.getSelectedColumn();
        
        if(evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(jtbItensEncomenda.getModel().getValueAt(jtbItensEncomenda.getSelectedRow(), 0)!= null
                    && jtbItensEncomenda.getModel().getValueAt(jtbItensEncomenda.getSelectedRow(), 1)!= null
                    && jtbItensEncomenda.getModel().getValueAt(jtbItensEncomenda.getSelectedRow(), 2)!= null
                    && jtbItensEncomenda.getRowCount()-1 == jtbItensEncomenda.getSelectedRow())
            {
                
                DefaultTableModel modelo = (DefaultTableModel)jtbItensEncomenda.getModel();
                modelo.addRow(new Object[]{});
            }
        }else if(evt.getKeyCode() == KeyEvent.VK_UP && !jtbItensEncomenda.isEditing()){
            if(jtbItensEncomenda.getRowCount()>1
                && jtbItensEncomenda.getModel().getValueAt(linhaSelecionada, 0) == null
                && jtbItensEncomenda.getModel().getValueAt(linhaSelecionada, 1) == null
                && jtbItensEncomenda.getModel().getValueAt(linhaSelecionada, 2) == null){
                
                Helper.RemoveRowJTable(jtbItensEncomenda);
            }
        }
    }//GEN-LAST:event_jtbItensEncomendaKeyPressed

    private void jtfRemetenteCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfRemetenteCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfRemetenteCodigoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Helper.CloseDialog(this, windowsBack);
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Helper.ShowDialog(this, new Pessoa(this));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbExluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExluirActionPerformed
        InitCamposBusca(false);
    }//GEN-LAST:event_jbExluirActionPerformed

    private void jtbItensEncomendaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbItensEncomendaKeyReleased

    }//GEN-LAST:event_jtbItensEncomendaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Encomenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Encomenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Encomenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Encomenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Encomenda(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ModalidadeFrete;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbBuscaCidadeDestino;
    private javax.swing.JButton jbBuscaCidadeOrigem;
    private javax.swing.JButton jbBuscaDestinatario;
    private javax.swing.JButton jbBuscaRemetente;
    private javax.swing.JButton jbCalcular;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbConsultar;
    private javax.swing.JButton jbExluir;
    private javax.swing.JButton jbGravar;
    private javax.swing.JButton jbIncluir;
    private javax.swing.JFormattedTextField jftDataCadastro;
    private javax.swing.JLabel jlStatusEncomenda;
    private javax.swing.JLabel jlValorTotal;
    private javax.swing.JRadioButton jrFreteNormal;
    private javax.swing.JRadioButton jrFreteRapido;
    private javax.swing.JRadioButton jrFreteSuperRapido;
    private javax.swing.JTable jtbItensEncomenda;
    private javax.swing.JTextField jtfBairroDestino;
    private javax.swing.JTextField jtfBairroRemetente;
    private javax.swing.JTextField jtfCepDestino;
    private javax.swing.JTextField jtfCepRemetente;
    private javax.swing.JTextField jtfCidadeDestinoCodigo;
    private javax.swing.JTextField jtfCidadeDestinoNome;
    private javax.swing.JTextField jtfCidadeOrigemCodigo;
    private javax.swing.JTextField jtfCidadeOrigemNome;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfComplementoDestino;
    private javax.swing.JTextField jtfComplementoRemetente;
    private javax.swing.JTextField jtfDestinatarioCodigo;
    private javax.swing.JTextField jtfDestinatarioNome;
    private javax.swing.JTextField jtfNumeroDestino;
    private javax.swing.JTextField jtfNumeroRemetente;
    private javax.swing.JTextField jtfRemetenteCodigo;
    private javax.swing.JTextField jtfRemetenteNome;
    private javax.swing.JTextField jtfRuaDestino;
    private javax.swing.JTextField jtfRuaRemetente;
    // End of variables declaration//GEN-END:variables
}